### ISSUE TITLE
can not disable the horization scrolling 

### ISSUE THREAD

**Issue by shirleyYing** [hammerjs/hammer.js#1022]
hi,I just want the vertical scrolling.but it not working . the code is following. 
`   
    let myElement = document.getElementById('app');
    this.mc = new Hammer.Manager(myElement,{touchAction:'pan-y'});
    this.mc.add(new Hammer.Pan({direction:Hammer.DIRECTION_VERTICAL}));
    this.mc.add(new                        Hammer.Swipe({direction:Hammer.DIRECTION_VERTICAL})).recognizeWith(this.mc.get('pan'));
`
I want to know the solution

**Comment by arschmitz** [comment]
just in the bit of code you have here you have a few issues. First vertical swipe and scrolling don't work together they are the same action. Second `recognizeWith` takes a string.

Im going to close this since its a question not an issue with the library. For help or questions please try stack overflow or #support in our slack channel
