### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by oste** [hammerjs/hammer.js#1034]
Hello,

It appears there is an issue with the current release. This file did not work for me https://github.com/hammerjs/hammer.js/blob/master/hammer.js but this one does http://hammerjs.github.io/dist/hammer.js

I am a bit confused because the dist file is dated 2016-04-23 and the one in the GH repo is 2016-09-30 but both have the same version.

I did not get any errors from the 2016-09-30 file, it just didn't work. I will try to provide more details but maybe this is something obvious that went wrong with the build.

Thanks

**Comment by runspired** [comment]
@oste the file was simply built later and represents incremental updates since the official release that will become the next release. Master should be in working order but if not and you can figure out why not please open an issue :) We recently reconfigured our build setup.

If you check, you'll notice this file with the tag for 2.0.8 is the file you were looking for: https://github.com/hammerjs/hammer.js/blob/v2.0.8/hammer.js

**Comment by runspired** [comment]
although, I did just notice that in 2.0.8 tagged we forgot to bump the version from 2.0.7 :/ apparently we got it right for the dist but not in that commit

**Comment by oste** [comment]
@runspired I see, yeah not too sure what the issue was with the master build. I thought that would be the same as the dist but apparently its actually a build of master. 

Thanks. I will see if I can find some time to track down the issue but kind of unfortunate that it seemed to just return and do nada.
