### ISSUE TITLE
swipeleft, swiperight, swipeup, swipebottom don't work on Chrome 29 for Android 

### ISSUE THREAD

**Issue by varemenos** [hammerjs/hammer.js#366]
I've been working on a simple swipe menu for a webapp of mine using Hammer.js while I noticed that the swipe events I've mentioned in the title don't get fired (can't debug because I have some adb issues with the drivers and windows 8.1). It only happens in Chrome for Android while the default Browser for android 4.1 works fine.

`Hammer.JS - v1.0.5`, `Chrome 29 for Android`

tested this in 2 Android devices: Archos Platinum 50 (phone), HP Touchpad (tablet).

**Comment by broweratcognitecdotcom** [comment]
using panleft panright worked for me. swipeleft and swiperight do not work.

**Comment by SKevo18** [comment]
Same issue here, still persists in Chrome 87.0.4280.88 (swipeleft, swiperight). I can use HammerJS in Chrome on desktop, but when I open DevTools and switch to the mobile layout, the actions don't get registered (or simply use Android mobile browser).

When I put `touch-action: pan-y;` in the touch area, it works. And doesn't kill scrolling (vertical scrolling). This works for Chrome 87 as of 8th January 2021. My specific use case was to show sidebar on horizontal swipe on Android devices, so if anyone is looking for a solution, putting `touch-action: pan-y;` in the HTML tag or the body tag (or the element you want to use gestures at) should work. Other solutions (such as `preventDefault()` didn't work for me), and I haven't tested it with horizontal scrolling, so I am not sure if it works.

So, as for HammerJS, possible solution might be to assign a `touch-action` CSS to the element that listens for gestures?

I know that this issue is very, very old and I am surprised that it still exists, so I have shared solution that worked for me in the case if anyone has the same error.

**Edit:**

> ---
> **WARNING:** Yes, unfortunately, this messes with other gestures, such as scaling and vertical scrolling.
>
> If you want to build a side navbar like me, then just use `pan` from HammerJS instead for your gestures, they work just normally.
>
> ---

• Mozilla documentation on `touch-action` - https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

According to that, `pan-y`:
> Enables single-finger vertical panning gestures. May be combined with pan-x, pan-left, pan-right and/or pinch-zoom.

This means that those gestures are technically disabled by default. `pan-y` enables them.

P. S.: If you're making side navbar like me and you're annoyed with the swipe back and forward page navigation, check [this question at Stackoverflow](https://stackoverflow.com/questions/30636930/disable-web-page-navigation-on-swipeback-and-forward)
