### ISSUE TITLE
hammer.js usage prevents scrolling of body on multi-touch devices

### ISSUE THREAD

**Issue by theirf** [hammerjs/hammer.js#470]
I'm using hammer.js for a gesture I've designed and I noticed that in my current implementation one can not scroll on multi-touch devices.

Why is that?

How can I fix that?

I don't need hammer applied to the body, just to the .dataCard class.

Here is a link to the site: http://goo.gl/iIdpLU

Here is the code:

    var hammertime = Hammer(document.body, {
		    transform_always_block: true,
		    transform_min_scale: 0,
		    drag_block_horizontal: true,
		    drag_block_vertical: true,
		    drag_min_distance: 0
		});

		var posX = 0, posY = 0, lastPosX = 0, lastPosY = 0, bufferX = 0, bufferY = 0, scale = 1,   last_scale, rotation = 1, last_rotation, dragReady = 0;

		hammertime.on('touch drag dragend transform transformend', function(ev) {
		    if ((" " + ev.target.className + " ").indexOf(" dataCard ") < 0) return;
		    else manageMultitouch(ev, ev.target); }); 
		    function manageMultitouch(ev, element) { 
		        switch (ev.type) { 
		            case 'touch': 
		                last_scale = scale;
		                last_rotation = rotation;
		                return;
		            case 'dragend':
		                lastPosX = posX;
		                lastPosY = posY;
		                return;
		           case 'drag':
		                posX = ev.gesture.deltaX + lastPosX; posY = ev.gesture.deltaY + lastPosY;
		                break; 
		          case 'transform':
		              rotation = last_rotation + ev.gesture.rotation;
		              scale = Math.min(last_scale * ev.gesture.scale, 10);
		              break;
		     }
		    if(scale <= 0.5) $(element).hide('clip').remove();
		    if(scale > 1.0) $(element).addClass('focused');

		     var transform = "translate(" + 0 + "px," + 0 + "px) " + "scale(" + 1 + "," + scale + ")";
		    var style = element.style;
		    style.transform = transform;
		    style.oTransform = transform;
		    style.msTransform = transform;
		    style.mozTransform = transform;
		    style.webkitTransform = transform;
		    }

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1

**Comment by kenpeter** [comment]
I have a similar issue. I am using joomla 3.4 and hammer.js 0.6.4. This is my test site: http://test.amberaviation.com.au. The code using hammer is here: http://test.amberaviation.com.au/templates/bt_travel/html/mod_bt_tabs/themes/default/js/default.js
On phone, it is not able to scroll. Set prevent_default: false, allow me to scroll, but experience not very good.

I realise that if I assign <a href="javascript:void(0)"> to images, when finger scroll the image, it is able scroll, but the text is not able to scroll, since it doesn't have <a href="javascript:void(0)"> around it. Any idea how to allow the site to scroll
