### ISSUE TITLE
Swipe events really hard to trigger on android and ipad

### ISSUE THREAD

**Issue by morkeleb** [hammerjs/hammer.js#52]
I just tested on the latest ipad and android 4.0, both have trouble activating the swipes.
I changed the swipe_time and swipe_min settings, increasing them made it easier on the ipad, but nearly impossible on the android device.

I only needed swipe so I changed to use http://www.netcu.de/jquery-touchwipe-iphone-ipad-library which work like a charm when swiping. I'm not sure what the changes in the swipe detection algorithm is but it might be interesting to take a look.

**Comment by csga5000** [comment]
I added hammer to this project because I figured it would reliably detect touch events on mobile devices.  So I was surprised when it wasn't.  Gesture was nearly impossible to trigger.  Spent a while trying to get it work.  Part of that I think is that the default min velocity is insanely fast on a device where the ppi is really high.  Because I had to flick my finger as fast as I could to trigger it.  Setting it to 0.01 instead of 0.3 fixed that.  But for some reason the event would never fire when I wasn't inspecting the webview via chrome://inspect and usb.  I would log in the callbacks and get no logs even though i see any other logs created.  Then I web debug over USB and though the console doesn't contain any logs for these events (though it has other logs) it starts logging events when I try swiping AFTER I opened the debugger.  Really weird, but this was what happened to me every time.  Perhaps it was do to a performance drop in the js/html, or perhaps something weird changes with event handling - but I'm pretty certain that's what was happening, I tried several times.  I tried doing something with "drag" like jtangelder suggested but I couldn't get the drag event to fire on mobile.

So I just wrote my own quick hack for detection.  Took less time to code then I spent trying to get hammer to work and seems reliable from my testing:

```
function SwipeDetect() {
	var MIN_DIST = 20;

	var self = this;
	this.mx = null
	this.my = null
	this.onLeft = null;
	this.onRight = null;

	this.handleStart = function(evt) {
		if (!evt.pageX)
			evt = evt.changedTouches[0]
		self.mx = evt.pageX
		self.my = evt.pageY
	}
	this.handleEnd = function(evt) {
		if (!evt.pageX)
			evt = evt.changedTouches[0]

		var dx = evt.pageX-self.mx
		var dy = evt.pageY-self.my

		if ((Math.abs(dx)/2) > Math.abs(dy) && Math.abs(dx) > MIN_DIST) {
			if (dx < 0 && self.onLeft) {
				self.onLeft()
			}
			else if (dx > 0 && self.onRight) {
				self.onRight()
			}
		}
	}

	window.addEventListener("touchstart", this.handleStart, false)
	window.addEventListener("touchend", this.handleEnd, false)
	window.onmousedown = this.handleStart
	window.onmouseup = this.handleEnd

}
var sd = new SwipeDetect();
sd.onLeft = function(ev) {
	$scope.navOpen = false
	$scope.$apply()
}
sd.onRight = function(ev) {
	$scope.navOpen = true
	$scope.$apply()
}
```

It's a quick hack, and not brilliantly engineered but it works for my purposes.
