### ISSUE TITLE
main window with swipe made with hammer and inside content with jquery ui draggable, conflict !

### ISSUE THREAD

**Issue by mikyweb** [hammerjs/hammer.js#558]
Hello i have the main html page called "index.html" with inside an iframe.
Inside the iframe, i load a html page called "content.html" where i use jquery ui draggable.

I have apply the Hammer swipe gesture on the body of the content.html and it work fine, but the drag width jquery ui is broken, not work.

Can you help me please ?

Thanks and compliments !

**Comment by arschmitz** [comment]
This issue is a mouthfull and really needs an example its also on version 1 im going to close this but if your still facing this issue open a new issue with a test case and i will gladly look i am the project lead on hammer now and i also work on jQuery UI so i will definitely look into any incompatibilities
