### ISSUE TITLE
Velocity at end of pan alway non-zero

### ISSUE THREAD

**Issue by mkv123** [hammerjs/hammer.js#620]
With a mouse doing the following: mouse down, move, stop for 1s, mouse up -> always non-zero velocity. 

As the mouse pointer wasn't moving for 1s, I would expect zero velocity at mouse-up i.e. panend.

This makes kinetic panning always fling the panned surface even when desperately trying not to.

**Comment by runspired** [comment]
This codepen shows that small pauses have near zero velocity and long pauses have zero velocity, which would be the correct behavior.  http://codepen.io/runspired/pen/MwxaBV?editors=101

**Comment by LeJared** [comment]
I've run into the same bug when i created a momentum-scroll functionality via hammerjs.
I've provided a reduced test case here: http://codepen.io/LeJared/pen/WvmZxm

The Bug can be reproduced best on Chrome when used on a **Windows 8/10 touch-device** (e.g. Surface Pro or Notebook width touch display). IE11 and Edge are affected too, but they don't work in this codepen.

**Bug**
You can scroll the two panels in the codepan via mouse-drag or touch-drag. It then will decelerate based on ```e.velocityY``` on ```panend```. The deceleration in the left panel often does not work on affected setups (e.g. Chrome/IE Touch on Windows) and stops immediately due to the ```e.velocityY``` being 0 or near 0 on ```panend```.
On the right panel I fixed it by using some kind of heuristik, to determine, when to use ```e.velocityY``` of the *last* ```panmove``` right before ```panend``` instead of the ```e.velocityY``` of ```panend``` itself. This case works perfectly on all setups.
It also shows, that ```e.velocityY``` might be some **thousend px per second** on the last ```panmove``` and then suddenly drops to **0** on ```panend```.

*Please reconsider reopening this bug.*

**Comment by arschmitz** [comment]
@LeJared it sounds like you want the opposite. This bug was saying should always be zero at the end it sounds like your saying you want it to be non zero.

The problem in both of these is that this works on a timed interval. because the granularity of mousemove / touchmove / pointermove is very dependent on several factors ( including the page it self and the other things your doing ) both the time and distance between events can vary greatly. So if your last 2 events happen to occur only a few pixels apart or even in the same place ( based on the timing event loop ) they will correctly have a very small velocity. This is not a bug its just how the browser works there is no guaranteed granularity in timed loops or events within the browser. 

I think the best way to work around the to do something like a momentum scroll would be to average the velocity for the last several events instead of just looking at the last one. 

> It also shows, that e.velocityY might be some thousend px per second on the last panmove and then suddenly drops to 0 on panend.

Yes your page is very very simple so there is almost nothing else happening in the event loop so the page runs very fast this means that the end even is fired near instantly after the move event. so there is essentially no difference in position and therefore no velocity. 

as a side note on your codepen in testing very briefly i believe the left panel which you did not fix generally worked better for me. i found that too often i left the top of the window when doing momentum scrolling which generally still worked on the "unfixed" pen where as the fixed one stoped as soon as i left the window

**Comment by LeJared** [comment]
You're right. I misunderstood that issue.

My problem is that i expect the ```e.velocityY``` on ```panend``` to be the same as on the last ```panmove```. I don't see any reason why it should not. Am I missing something?

But what definitely happening is, that even on fast moves ```panend``` delivers ```e.velocityY``` 0 though the finger never stopped moving. This interrupts the movement even if the user performed it's gesture well.

But if I get yo right, this means that the velocity value of panend is not reliable, because it depends, if panend is fireed very qulicky or very slowly after the last touchmove. So indeed, interpolation might be the best way.

May be this is a feature, hammerjs could provide out of the box in a future release: interpolated velocity with respect for an intentional stop by the user (e.g. no moveevent for more than 150ms or something).

**Comment by arschmitz** [comment]
@LeJared no `panend` should not be the same as the last `panmove` they are different events and happen at different times and therefore have different values you should never rely on these being the same. 

For your case I think what it sounds like you really want to fix your case is the LAST `panmove` to get this simply save each `panmove` to a variable and check this and clear it on `panend`
