### ISSUE TITLE
iOS / Android: Events stop when touched HTML Element is removed from the DOM

### ISSUE THREAD

**Issue by benwick** [hammerjs/hammer.js#645]
Hello,

I have a big problem with hammer js on iOS devices: There seems to be a problem with events and removed HTML elements. Say we have a container, on which we use hammer with one panstart and one panmove handler. Inside we have a HTML element, which we start dragging. When the the element is removed during some logic inside the panmove handler, no event will be fired anymore, even if the finger is still on the device and moving. Desktop browsers don't show this annoying behaviour. Any suggestions?

**Comment by runspired** [comment]
Losing track of user input because the underlying dom element has been removed is likely expected and acceptable behavior. Closing unless @arschmitz feels otherwise.

**Comment by LeJared** [comment]
This is actual specified behavior on Touch-Events and thus can not be fixed in hammerjs.

When perfoming a touch gesture all subsequent events are send to the exact same Element where the gesture startet. This means, all touchmove Events are send to the same element where touchstart was fired. This still happens, when the corresponding element is removed from the DOM. Because of the the touchmove ebent send to the elemen will not bubble through the DOM to your listener any more. This is specified browser behavior and can not be changed.

If you want to caputure the touchmove-event after removing the node from the DOM you have to reattach the event.target vom touchstart (panstart) to the DOM within the element your hammer-instance is bound to and hide it any other way (e.g. display:none).
