### ISSUE TITLE
Hammer 2.0.x not working with TUIO

### ISSUE THREAD

**Issue by frostney** [hammerjs/hammer.js#699]
I am using [Caress](http://caressjs.com/) (server + client) to access TUIO data in the browser and be able to react to touch events. It's all working well with Hammer 1.1.x. This is basically my example code:
```javascript
var hammertime = Hammer(element, {
  preventDefault: true
});

hammertime.on('drag', function(ev) {
  // Stuff happening here
});
        
hammertime.on('pinch', function(ev) {
  // Stuff happening here
});
```

I wanted to upgrade to Hammer 2.0.x and adjusted my code to this:
```javascript
var hammertime = Hammer(element);

hammertime.get('pan').set({
  direction: Hammer.DIRECTION_ALL 
});

hammertime.get('pinch').set({ enable: true });

hammertime.on('pan', function(ev) {
  // Stuff happening here
});
        
hammertime.on('pinch', function(ev) {
  // Stuff happening here
});
```

Unfortunately, with Hammer 2.0.x none of the events get triggered. I've tested it both with [TongSeng](https://github.com/fajran/tongseng) and a TUIO touchscreen.

The problem occurred when I used Hammer 2.0.4 and Chrome 38.

I've seen [a similar issue popping up on StackOverflow](http://stackoverflow.com/questions/24872968/hammer-js-2-0-and-tuio), but with no indication on how to fix or circumvent it.

**Comment by runspired** [comment]
While this issue is specific to the TUIO platform, looking into this it seems that #808's shift to pointer events might alleviate it.

Side note for TUIO users: Hammer 2.0.4 also works with the hammer touch emulator, which appears to be similar to what https://github.com/borismus/MagicTouch is doing, so it's probably currently possible to make TUIO work on Hammer 2.0.4 at the event generation layer.

Closing in favor of #808.
