### ISSUE TITLE
Tap firing twice

### ISSUE THREAD

**Issue by MadhuSudhanBhaskar** [hammerjs/hammer.js#727]
I am using Angularjs, for events I am using hammer.js . I have a new version on hammer.js on my application. The tap is binded my directive, when I tap or touch on my mobile device its firing twice.

**Comment by RyanMullins** [comment]
@MadhuSudhanBhaskar I'm the maintainer of [Angular Hammer](https://github.com/RyanMullins/angular-hammer) and have been encountering a similar problem. When you get a chance, take a look at my issue (#742) , which details what we believe to be the problem, and compare with your own code/experience. If you find it to be the same I would recommend closing this issue and watching my issue.

**Comment by runspired** [comment]
@RyanMullins Did you miss the part of the docs that suggests preventGhostClicks?

http://hammerjs.github.io/tips/

https://gist.github.com/jtangelder/361052976f044200ea17

**Comment by RyanMullins** [comment]
Nope. Please read the details of my issue. It's a very different problem related to capturing both TouchEvents and MouseEvents fired from a single click but milliseconds apart.

**Comment by RyanMullins** [comment]
@runspired Unless I'm completely misinterpreting the point of PreventGhostClicks, which I view as a way to stop _other_ handlers from being fired when after a Hammer handler responds.

**Comment by RyanMullins** [comment]
@runspired this may even be a problem particular to Angular. If it is, it's because of the Angular execution context where it effectively adds a second run loop inside of the JavaScript run loop, so it could be that the secondary mouseup event is being triggered before the PreventGhostClicks functionality in the Angular context has a chance to respond. If that is the case, then the solution I want will eliminate the need for PreventGhostClicks.

**Comment by MadhuSudhanBhaskar** [comment]
@Ryan Sure I will check your issue and close mine.

**Comment by runspired** [comment]
Closing in favor of the meta issues for this.
