### ISSUE TITLE
Looking for a maintainer.

### ISSUE THREAD

**Issue by jtangelder** [hammerjs/hammer.js#749]
I'm looking for someone who would like to maintain Hammer.js. Unfortunately I just don't have enough time left for the project due a new job, and don't have use the library myself these days. 

Requirements of a new maintainer should be that he is aware of the impact of the changes, since the project is being used in [quite a lot of websites/apps](http://libscore.com/#Hammer). It has almost 10K stars, so it comes with some responsibility.

Some of the key features of Hammer;
- Speed; Hammer is being called on every mouse/touch-move, so keep the code as simple as possible
- Clean of overhead/sugar; To keep the library small and focused, I dont'want all kinds of small additions to support X feature for some edge cases. Hammer is/should be quite modular so some hooks are fairly easy to implement.
- Small minified filesize.
- No dependencies.

If you are interested, and can find yourself in the points above, please contact me!

https://twitter.com/jorikdelaporik

**Comment by gagan-bansal** [comment]
just want to follow this Q

**Comment by DimitryDushkin** [comment]
wow, really no one for project with 10k+ stars?(

**Comment by enrichit** [comment]
@DimitryDushkin I doubt many people are qualified.

**Comment by runspired** [comment]
And of those that are, they likely already maintain or are heavily involved in other projects.

I'd be down to be part of a team of maintainers, but I know I couldn't devote nearly enough time on my own.

**Comment by enrichit** [comment]
@runspired I could also probably help out a bit. I'm pretty solid with JS nowadays, I wouldn't want to be the primary maintainer though.

**Comment by sbmaxx** [comment]
When i have a pull request not merged from Aug, 2014 in polymer-gestures https://github.com/Polymer/polymer-gestures/pull/50 (and more https://github.com/Polymer/polymer-gestures/pulls ) they suggested me to use hummer.js. And now what? No maintainer? That's very sad. 

Pointer-gestures still use it's own polyfill for pointer-events, while polymer team transfered pointer-events repo to jQuery foundation https://github.com/jquery/PEP.

Strange fate of all libs of pointer-events/poingers-gestures. Why there are no people wanting to maintain them? :)

**Comment by stephanebachelier** [comment]
@sbmaxx it's not that people does not wan't to maintain a lib, but it requires time, motivation and some skills, and I bet lots of people don't have lots of time. As pointed by @jtangelder in the case of Hammer.js it comes with responsability, as being a 10k stars project.

I would like to help maintaining Hammer.js but currently I'm already involved in others projects, so at this time I can't be the only one.

By the way a triage of the issues by closing outdated issues, add some labels, would be really helpful. It might also help a little bit.

**Comment by picitujeromanov** [comment]
That's true, the number of opened issues is quite repellent.

**Comment by gagan-bansal** [comment]
Initially issues can be labeled first as 'bug' or 'enhancement' etc. 
That will show how much real work is required.

**Comment by schue** [comment]
Maybe we could organize a "bug crush" event or something. Not quite the same as having a maintainer but a community building effort.

**Comment by rafde** [comment]
Ask the jQuery Foundation to adopt it. They did it for jquery mousewheel.

http://blog.jquery.com/2014/10/27/jquery-foundation-adopts-mousewheel-plugin/

**Comment by runspired** [comment]
I feel as though there are enough people in here (myself included) willing to be a partial maintainer that we could form a team and take care of this.  I'm 100% on board with the idea of starting by working through the issues to 

- close (and reference) duplicates
- close resolved issues or non-bugs (there seems to be a number of issues relating implementation errors, not hammer errors, which might be helped by improving the docs in some areas).
- label bug/enhancement

I think just organizing and going through the issues will give us a much better idea of the amount of work needed to be done now, as well as enable prioritization for a "bug crush" event.

**Comment by runspired** [comment]
I believe along with myself it seems that

@enrichit @schue @gagan-bansal @stephanebachelier @picitujeromanov 

would all be willing to help out in some capacity, at least for an initial issue cleanup.

**Comment by gagan-bansal** [comment]
For initial issue cleanup before "bug crush" event I am in.

**Comment by picitujeromanov** [comment]
I'm in

**Comment by enrichit** [comment]
+1

**Comment by DimitryDushkin** [comment]
I would like to help to develop Hammer.js, but I'm not qualified to be the main maintainer.)

**Comment by stephanebachelier** [comment]
@runspired I'm in.

**Comment by sbmaxx** [comment]
+1 to spread developing to many people ;)
i wanna help

**Comment by runspired** [comment]
@jtangelder would a multiple maintainer setup be acceptable?

**Comment by jdhiro** [comment]
I use Hammer professionally, so I too have an interest in seeing continued development here. I'm willing/able to also be a partial contributor, but it's unlikely that I could be a full-time maintainer.

**Comment by tangst** [comment]
Most of the best open-source projects on Github have more than one maintainer.  It's good policy as it provides developer redundancy and allows everybody's partial free time to focus on particular areas.  @jtangelder should strongly consider taking up the offers of the people who can volunteer some free time.  Having "official" maintainers will let developers know that the project is still active in some form.  

jQuery Foundation may not be the best way to go, because HammerJS isn't a jQuery plugin.

As a current user of HammerJS for some small projects, finding this announcement saddens me greatly.  If HammerJS is not transitioned to a maintainer or team of maintainers, I'm going to have to find something else.

**Comment by enrichit** [comment]
@tangst If there is no response there's no reason one of us couldn't fork it, give it a name change and run it as a different project. We could even merge it back into hammer if this repository is opened up again. Some admin difficulties involved with that (mainly issue migration and the problems surrounding a project name change) but it's possible.

No need to "find something else" unless you have a specific issue, the library works well as it stands I find.

**Comment by runspired** [comment]
@enrichit @tangst I did give a little thought to forking it since @jtangelder has been silent so long.  Porting issues across the fork, and the fact that hammer already has a hammerjs org with other hammerjs libs are why I've not done that.  It may ultimately become necessary.

**Comment by tangst** [comment]
@enrichit I can probably keep using it for a while longer, since I'm only using on small projects.  

My viewpoint, as an ordinary user of HammerJS, is that I find it telling that there are a handful of people like yourself offering to work on it part-time in small chunks for the last month or so, and jtangelder still hasn't said anything.  If he is holding out for a person who can comply with 100% of his requirements, then HammerJS will likely die a slow death, as an "abandoned" project.  Consequently, I would be weary of using it on any larger projects or recommending it to others.  Other developers who use it will notice this announcement eventually and probably devise migration plans.

HammerJS has seemingly reached the point that it's no longer just jtangelder's "baby."  With 10,000 stars on the project, I would rather jtangelder release his creation to the community and let the community decide its fate if he has other things to do now.  John Resig did it with jQuery.

I know some really good projects have come from forks, but with bower (one example) pointing to the main Github repo, the project should be transferred to new owners.

**Comment by enrichit** [comment]
@runspired @tangst Exactly, I was only suggesting it as a last resort. Of course it would be better off as it is, being a well established project.

Still, needs must when the devil drives.

**Comment by schue** [comment]
I think forking Hammer.js would be the same thing as volunteering to be the new maintainer.

**Comment by enrichit** [comment]
Not really. You can add multiple people to collaborate on merging requests and dealing with issues. A handful of collaborators managing many contributors is quite normal, you dont have to take the entire burden just because the repository is under your account.

**Comment by jtangelder** [comment]
Hi guys, I am still following this thread, but currently (and unfortunately) have other things on my mind then this project. I guess I can find some time in the upcoming weekend to write a greater reply than this. 

Quick note of my thoughts; the project has become too big for me to handle, I can't manage a 10k on my own, and don't use it myself anymore. Like @tangst said; It's not my baby anymore. :-)

I would love to give it to the community, but I don't exactly know where to start with this, and how to choose someone for this. It would be sad if the project would die, but also if the project is getting into the wrong hands. 
If any of you guys has some interesting links or thoughts about this; please let me know.

**Comment by schue** [comment]
But the new person coordinating collaborators has effectively become the lead. 

Anyone who thinks they want to fork it should just take the reigns formally. The new maintainer can put a policy in place to spread the load as soon as they take over. Maybe everyone with more than 5 commits should get permission to process a merge request or something like that. 

> From: "enrichit" <notifications@github.com>
> Subject: Re: [hammer.js] Looking for a maintainer. (#749)

> Not really. You can add multiple people to collaborate on merging requests and
> dealing with issues. A handful of collaborators managing many contributors is
> quite normal, you dont have to take the entire burden just because the
> repository is under your account.

**Comment by runspired** [comment]
@jtangelder In brief, what I'd push for:

- A core team collectively responsible for final vote on new features / proposed refactors (not controlled by a single maintainer), and for accepting/proposing new maintainers.
- A bi-weekly core team meeting (via hangouts or similar) to go over outstanding issues, new feature requests, etc.
- A clear policy/process for community members to submit PRs (e.g. must be tested, must be a passing build, must PR into the `develop` branch, only change `src` don't commit the compiled files)
- Timely reviews of issues and PRs
- A maintained CHANGELOG
- A jsbin template for use in replicating issues when submitting a bug report
- A dedication to SemVer
- A transparent RFC process for new features.

You already put a lot of this into place, but it could be more clear, and I additionally think it would be amazing if you yourself would head up the core team during a transition period, ensuring that the process is put in place, that each member has a strong knowledge of the code base, and long term expectations.

**Comment by tangst** [comment]
@jtangelder Thanks for responding now.  Please find some time this weekend to formulate a full response and possibly provide immediate transition of the Github repository to someone.

Based on the amount of feedback in this thread, you could give full owner access of the HammerJS repository to @enrichit and @runspired and make a brief announcement on the repo's home page announcing a change of ownership.  I briefly checked their Github profiles, and they have contributed to lots of projects.  From there, they can add additional maintainers as needed.

As for HammerJS going to a "bad" owner, that might happen, but by then, you're off the project.  As long it's publicly known (i.e. tweet it, announce on developer lists, etc.) that you have decided to retire from HammerJS to pursue other interests, your developer reputation should remain intact.  The current owners of HammerJS can be fully blamed if they steer HammerJS into oblivion. :-)  If you don't want a corporate owner to get their hands on the code, you could mandate a GPL license or something similar in the code.  That's just the nature of having code given back to the community; there's always a risk.  You can't be too attached to your code, or you will never find successors to take your place, and then the code dies.

I don't really have any other suggestions.  If someone had the money and the paperwork skills, they could copy the jQuery Foundation format, and build a HammerJS Foundation to preserve the code and ensure that it's being steered correctly, but that's a lot of effort.

I don't want a fork as @schue suggested, because Bower, NPM, and a host of other unknown dependencies might be pointing to this repo.  Even if somebody were to fork it and fix bugs and make improvements, that person won't be able to advertise that development is still active.  The average developer (people in the trenches who are not on the bleeding edge of front-end development and just need to get the work done) only pay attention to official repos.  Forks are generally avoided.

As a general user of HammerJS, I'm not expecting the repo to be completely issue free.  Nor do I expect the new maintainers to try to do a large "bug crush."  What I do want to see is either some form of progress, as in a recent commit that solves an issue or two or a status update on the HammerJS Github home page if there isn't anything going on (i.e. "We haven't done any commits recently, but we're looking to fix a few things in June 2015").  It's ok if maintainers need to take a vacation/break; they just need to say something on the repo instead of disappearing.

**Comment by schue** [comment]
> I don't want a fork as @schue suggested, because Bower, NPM, and a host of other
> unknown dependencies might be pointing to this repo. Even if somebody were to
> fork it and fix bugs and make improvements, that person won't be able to
> advertise that development is still active. The average developer (people in
> the trenches who are not on the bleeding edge of front-end development and just
> need to get the work done) only pay attention to official repos. Forks are
> generally avoided.
Please read my message more carefully. I did not suggest a fork. I suggested that anyone motivated enough to attempt to fork should instead become the maintainer. That would be the opposite of suggesting a fork.

**Comment by tangst** [comment]
@schue I'm sorry.  I read your post again.  I see the difference.  I edited my post with the correction.

**Comment by schue** [comment]
@tangst, no worries.

One interesting management viewpoint is the "Collective Code Construction Contract" used by 0MQ. 

You can view it at http://rfc.zeromq.org/spec:22

**Comment by gagan-bansal** [comment]
@jtangelder seems you are quite busy, but hope you can give some direction based on @runspired suggestions.

**Comment by kenjikato** [comment]
Any movement on where hammer.js is going?

**Comment by schue** [comment]
I've been heads down on some other things so... not from my side. I am, however, going to start some mobile intensive work soon and I'm sure hammerjs is going to play a role in that.

**Comment by jtangelder** [comment]
Good news everybody, @arschmitz is going to help developing and maintaining Hammer. Alex is currently being involved with jQuery Mobile and has lots of experience with mobile development. I'm very thankful that he is offering his time and efforts into this project, and I'm excited of our shared future plans. 

Our first steps are solving the current open issues and PRs. Next steps will contain writing a more modular version of Hammer, improving tests and hopefully expand the project team. More on this later.

I'm looking forward in working together with Alex and the community to keep this project alive :dancer:

**Comment by runspired** [comment]
@jtangelder great to hear!
@arschmitz My offer to help maintain is still open, if you both would like the help solving current issues and PRs I'd love to pitch in.

**Comment by arschmitz** [comment]
@jtangelder Thank you for the intro! Can't wait to help get the project moving again. I created an IRC channel for development and support #hammer.js on freenode would love to see any one interested in helping in there!

@runspired Awesome i would definitely appreciate any help. One of my first steps for the long term for the project is to try to build a team around this project so its not dependent on any one person to continue. Would love to have you help with that. 

On that note i opened #800 to help start the team building process.

**Comment by jdhiro** [comment]
Awesome news!

**Comment by tangst** [comment]
Great to hear.  I can stop my migration plans.

**Comment by arschmitz** [comment]
Anyone wishing to join us in discussing future development is welcome in our new slack channel you can get an invite @ http://hammerjs-slackin.herokuapp.com/

**Comment by rafde** [comment]
Is https://gitter.im/hammerjs/hammer.js an option for live medium?

**Comment by arschmitz** [comment]
@rafde see #800 Im going to close this now that this is settled and #800 is handling anything remaining.

**Comment by hackhat** [comment]
What happened? Is still not maintained
