### ISSUE TITLE
swipeup issue

### ISSUE THREAD

**Issue by coshen** [hammerjs/hammer.js#764]
I have a problem with the swipeup method,when I　use the method like this:
 var hammertime = new Hammer(document.querySelector("#show"), { });
hammertime.get('swipe').set({ direction: Hammer.DIRECTION_UP });
hammertime.on('swipe', function(ev) {
 	         dosomething();
}); 
the method can be use but the side scroll bar can't be triggered any more,when I have a page with scroll bar,what should I do to handle this?

**Comment by bafxyz** [comment]
same here, did you found a solution?

**Comment by pankaj-arunsingh** [comment]
any solution yet?

**Comment by hamosapience** [comment]
You can always set touchAction to 'auto'. This will enable browser's native scroll behavior. Still, there are some problems. For example, in Android Native browser touchAction: 'auto' will break swipe detection, which is really bad and actually is a bug.

**Comment by arschmitz** [comment]
Is anyone seeing this issue on anything besides the old android browser? If not i'm going to close this. There is actually no way for swipeup / down to work on old android browser due to how touch events are handled you must either `preventDefault ` on the events which stops native scrolling or you stop getting touch events. 

@rbyers from the chrome team and I have talked about this a lot and on the native chrome browser there is just no real solution other then to try to "guess" based on the deltas intent based on just the 2 events you get. However this would not work on other platforms.

**Comment by RByers** [comment]
> There is actually no way for swipeup / down to work on old android browser due to how touch events are handled you must either preventDefault on the events which stops native scrolling or you stop getting touch events.

I believe this is true of Android 4.0 and prior.  Android 4.1 [should be better](https://code.google.com/p/android/issues/detail?id=4549).

> @rbyers from the chrome team and I have talked about this a lot and on the native chrome browser ...

Did you mean the native Android browser, or in Chrome?  In most modern browsers (Chrome, Safari and probably others) there are limits to the ability for script to block scrolling.  Any UX that is hard to reliably distinguish between touching and scrolling is going to be problematic.  Eg. any solution for detecting "swipe up" on something that can also be scrolled up is going to be problematic (because "swipe up" should trigger a quick fling).

**Comment by arschmitz** [comment]
@RByers Yes i mean native andorid browser sorry about that. And yes even in modern browsers this is problematic and pretty hard if not impossible to support properly.

**Comment by runspired** [comment]
Closing as supporting gestures in the same direction as scrolling isn't currently practical / possible. (ping @arschmitz )
