### ISSUE TITLE
Hammer events delegation and reuse of backbone view

### ISSUE THREAD

**Issue by oak-tree** [hammerjs/hammer.js#766]
I have an issue with creating two views (of the same kind) and use hammer. it only works on the first created view. 

## More info 

http://stackoverflow.com/questions/28722774/hammer-events-delegation-and-reuse-of-backbone-view

there is a runnable code inside the question that can reproduce this issue

**Comment by runspired** [comment]
These were all likely related to the leaked configs of Recognizers and Managers.

**Comment by oak-tree** [comment]
why did you close this one ?
it seems the bug is still there ( see the link above ). Moreover the link suggest to change  the following line 
https://github.com/hammerjs/hammer.js/blob/f20533d2566868034f7f2446f96128c17cb3e506/src/input/touch.js#L16

this.evTarget = TOUCH_TARGET_EVENTS;
to

this.evEl = TOUCH_TARGET_EVENTS;

**Comment by runspired** [comment]
I closed it because the issue was due to the leaked configuration.

**Comment by oak-tree** [comment]
what was the leaked configurations?

**Comment by oak-tree** [comment]
what was the leaked configuration?

**Comment by runspired** [comment]
All manager shared the same configuration object, and all recognizer options shared their own object as well.  This meant that if you created more than one instance of a manager or recognizer, last instance would override the configuration for all other existing managers and recognizers.

https://github.com/hammerjs/hammer.js/blob/f20533d2566868034f7f2446f96128c17cb3e506/src/input.js#L44

and 

https://github.com/hammerjs/hammer.js/blob/f20533d2566868034f7f2446f96128c17cb3e506/src/input.js#L70

Are how that in turn caused this bug to manifest.  It's fixed in 2.0.5.

**Comment by oak-tree** [comment]
cool, thanks!
