### ISSUE TITLE
Native scrolling does not work, even with preventDefault = false

### ISSUE THREAD

**Issue by DanielApt** [hammerjs/hammer.js#856]
From what I understand, setting `preventDefault` to `false` should allow native events to occur. When running the following code, native touch scrolling is still blocked:

```js
var mc = new Hammer.Manager(this.el, {preventDefault: false});

mc.add(new Hammer.Swipe({direction: Hammer.DIRECTION_ALL, velocity: 0.05, preventDefault: false}));

mc.on('swipeleft', function (e) {
     that.nextStream();
});
```

The only way to solve it is by adding:
```js
TouchEvent.prototype.preventDefault = function () {
     // do nothing, prevent native touch scrolling from being blocked
};
```

which is a hacky way of getting native scrolling to work in combination with swipe detection.

Is my usage of `preventDefault` in the options incorrect? How can I allow native scrolling in combination with a HammerJS swipe detector?

**Comment by runspired** [comment]
> Is my usage of preventDefault in the options incorrect?

Yes, that's not actually an option.  It is a method on the emitted gestures though, but it is't true by default.

Hammer does on some devices preventDefault automatically on the source event if the `touch-action` CSS matches values for which that is the expected behavior.

> How can I allow native scrolling in combination with a HammerJS swipe detector?

You can't swipe/pan on the same axis as scroll.  That doesn't make sense if you think about it.
For vertical scrolling and horizontal swiping, try `Hammer.DIRECTION_HORIZONTAL`
